Update increment_version.yml

diff --git a/.github/workflows/increment_version.yml b/.github/workflows/increment_version.yml
--- a/.github/workflows/increment_version.yml
+++ b/.github/workflows/increment_version.yml
@@ -25,15 +25,20 @@ jobs:
       run: |
         VERSION_FILE="MahjongCore/MahjongCore.csproj"
         VERSION_REGEX='<Version>([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)<\/Version>'
-        CURRENT_VERSION=$(grep -oP "$VERSION_REGEX" $VERSION_FILE | sed -E "s/$VERSION_REGEX/\1.\2.\3.\4/")
-        echo "Current version: $CURRENT_VERSION"
-        echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV
+        if grep -qP "$VERSION_REGEX" $VERSION_FILE; then
+          CURRENT_VERSION=$(grep -oP "$VERSION_REGEX" $VERSION_FILE | sed -E "s/$VERSION_REGEX/\1.\2.\3.\4/")
+          echo "Current version: $CURRENT_VERSION"
+          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV
+        else
+          echo "Version tag not found in $VERSION_FILE"
+          exit 1
+        fi
       shell: bash
 
     - name: Increment version
-      id: increment_version
       run: |
         CURRENT_VERSION="${{ env.current_version }}"
+        echo "Current version from env: $CURRENT_VERSION"
         IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
         MAJOR=${VERSION_PARTS[0]}
         FEATURE=${VERSION_PARTS[1]}
@@ -42,6 +47,7 @@ jobs:
 
         if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           PR_TITLE="${{ github.event.pull_request.title }}"
+          echo "PR title: $PR_TITLE"
           if [[ "$PR_TITLE" == *"[major]"* ]]; then
             MAJOR=$((MAJOR + 1))
             FEATURE=0
@@ -60,8 +66,8 @@ jobs:
         fi
 
         NEW_VERSION="$MAJOR.$FEATURE.$BUG.$BUILD"
-        sed -i "s/<Version>$CURRENT_VERSION<\/Version>/<Version>$NEW_VERSION<\/Version>/" $VERSION_FILE
         echo "New version: $NEW_VERSION"
+        sed -i "s/<Version>$CURRENT_VERSION<\/Version>/<Version>$NEW_VERSION<\/Version>/" $VERSION_FILE
         echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
       shell: bash
 
